"""add_planning_sessions

Revision ID: 21226a074d43
Revises: a76bf9e600b3
Create Date: 2026-04-17 01:18:12.036041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "21226a074d43"
down_revision: Union[str, Sequence[str], None] = "a76bf9e600b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop legacy langchain pgvector tables (no longer used)
    op.execute("DROP TABLE IF EXISTS langchain_pg_embedding CASCADE")
    op.execute("DROP TABLE IF EXISTS langchain_pg_collection CASCADE")

    # Create planning_sessions for multi-step travel planning flow
    op.create_table(
        "planning_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_room_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_room_id"], ["chat_rooms.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_planning_sessions_chat_room_id"),
        "planning_sessions",
        ["chat_room_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_planning_sessions_id"),
        "planning_sessions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_planning_sessions_updated_at"),
        "planning_sessions",
        ["updated_at"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "langchain_pg_embedding",
        sa.Column("collection_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column("document", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "cmetadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("custom_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["langchain_pg_collection.uuid"],
            name=op.f("langchain_pg_embedding_collection_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("langchain_pg_embedding_pkey")),
    )
    op.create_table(
        "langchain_pg_collection",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "cmetadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("uuid", name=op.f("langchain_pg_collection_pkey")),
    )
    op.drop_index(
        op.f("ix_planning_sessions_updated_at"), table_name="planning_sessions"
    )
    op.drop_index(op.f("ix_planning_sessions_id"), table_name="planning_sessions")
    op.drop_index(
        op.f("ix_planning_sessions_chat_room_id"), table_name="planning_sessions"
    )
    op.drop_table("planning_sessions")
    # ### end Alembic commands ###
