"""add_token_usage_and_cost

Revision ID: cf4b17ea6ee0
Revises: 21226a074d43
Create Date: 2026-04-17 01:47:11.786670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf4b17ea6ee0"
down_revision: Union[str, Sequence[str], None] = "21226a074d43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages", sa.Column("prompt_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "chat_messages", sa.Column("completion_tokens", sa.Integer(), nullable=True)
    )
    op.add_column("chat_messages", sa.Column("total_cost", sa.Float(), nullable=True))
    op.add_column(
        "users",
        sa.Column("total_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "users",
        sa.Column("total_cost", sa.Float(), nullable=False, server_default="0.0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "total_cost")
    op.drop_column("users", "total_tokens")
    op.drop_column("chat_messages", "total_cost")
    op.drop_column("chat_messages", "completion_tokens")
    op.drop_column("chat_messages", "prompt_tokens")
    # ### end Alembic commands ###
